### ISSUE TITLE
Duplicate text in descriptions of components for frameworks

### ISSUE THREAD

**Issue by enchart** [iconify/website#14]
The text on the [Iconify for React](https://iconify.design/docs/icon-components/react/) page is duplicated and is the same for the pages of all the other frameworks. ([Vue](https://iconify.design/docs/icon-components/vue/), [Svelte](https://iconify.design/docs/icon-components/svelte/) etc.)

**Comment by cyberalien** [comment]
Thanks for reporting!

Those pages do share sections and text was supposed to be replaced, but it isn't replaced. That's a bug.

**Comment by cyberalien** [comment]
Fixed
