### ISSUE TITLE
Images broken in page https://iconify.design/docs/design/figma

### ISSUE THREAD

**Issue by yunsii** [iconify/website#15]
![image](https://github.com/iconify/website/assets/18096089/cd8425ed-3925-4e71-b071-c141bbc7c546)

**Comment by yunsii** [comment]
I try to change `https://iconify.design/docs/assets/images/plugins/figma_code.png.html` to `https://iconify.design/assets/images/plugins/figma_code.png.html`, it works. After further investigation, it looks like route redirection is wrong. `docs.iconify.design` redirect to `iconify.design/docs` currently.

**Comment by cyberalien** [comment]
Thanks a lot for noticing!

Fixed.
