### ISSUE TITLE
Navigation between sets not working properly

### ISSUE THREAD

**Issue by JarolinVargas** [iconify/website#16]
When searching an icon, selecting, then going back to the 'Browse icon sets' page and searching again using the same keyword; I'm taken back to the previously selected icon page. Not the search results page.

**Comment by cyberalien** [comment]
Thanks for noticing and reporting!

Unfortunately that cannot be fixed because icon sets website is a mess. I'm rewriting whole thing, it will be a completely different code that has nothing in common with current website.
