### ISSUE TITLE
Toggle using `"` and `'` in SVG code

### ISSUE THREAD

**Issue by noah-severyn** [iconify/website#18]
Hello! Would you consider supporting the option to toggle between using `"` and `'` in HTML code in the SVG copy textbox? 

I am using the code in an application that expects the SVG info as a string and I need to replace all `"` with `'` so it doesn't get confused.

**Comment by cyberalien** [comment]
No, sorry. This is a very rare use case.

Most programming languages have multiple ways of creating strings that do not require messing with content: single quotes, backtick, heredoc and other methods. So it is a very rare use case.
