### ISSUE TITLE
SVG Framework script tag

### ISSUE THREAD

**Issue by gardenerik** [iconify/website#19]
On the [SVG Framework](https://iconify.design/docs/icon-components/svg-framework/), when you copy the `<script>` tag in the Usage section, the code that gets copied is different from the shown code.

Displayed:

```html
<script src="https://code.iconify.design/3/3.1.1/iconify.min.js"></script>
```

Copied:

```html
<script src="https://code.iconify.design/2/2.0.0/iconify.min.js"></script>
```

It [looks like](https://github.com/iconify/website/blob/4f9d5e0191991ea4de79704a11c25556fb3f0ea2/docs/icon-components/svg-framework/index.md#L31-L36) the version is hardcoded in the copy.

**Comment by cyberalien** [comment]
Thanks a lot for noticing and reporting!

Fixed.
