### ISSUE TITLE
bug: icon detail modal

### ISSUE THREAD

**Issue by mahmutoz** [iconify/website#28]
<img width="993" alt="Screenshot 2024-05-16 at 12 26 06" src="https://github.com/iconify/website/assets/49031200/d41ccfd6-0857-4a65-88e1-d1daaea26045">

Hello,

I couldn't close modal. Because the buttons are intertwined.

Icon: streamline:money-graph-arrow-decrease-down-stats-graph-descend-right-arrow

**Comment by userquin** [comment]
we need to review some styles...

**Comment by cyberalien** [comment]
Thanks a lot for reporting!

Fixed. Will will be deployed tomorrow after icon sets update.
