### ISSUE TITLE
Using the icon drawer is challenging without a fixed height.

### ISSUE THREAD

**Issue by chioio** [iconify/website#30]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/de7632cf-e3d2-4258-bbbc-6983e6a1a9ea">
the other:
<img width="1705" alt="image" src="https://github.com/user-attachments/assets/023f0de6-4b23-4515-82a0-cb1df6096c7e">

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed. It now remembers last height and prevents content from jumping down.
