### ISSUE TITLE
Icon drawer gets too tall sometimes

### ISSUE THREAD

**Issue by nirewen** [iconify/website#33]
Maybe related to #30

## Issue

The icon drawer doesn't have a max height and is not scrollable.

This is fine for icons that don't add too much information to the drawer, like regular icons

But there's a specific set that I use, Fluent Emoji, that has many colors, in which the website lists.

Works fine for few colors, like this:

![image](https://github.com/user-attachments/assets/d1608929-0207-4df0-aa11-b4f5c7072357)

But the drawer goes bonkers when you select an emoji with many colors:

![image](https://github.com/user-attachments/assets/e5497338-ece6-4c76-9244-a27d0a96aa2c)

The only fix, for now, is to reload the page, or zoom out far enough to close the drawer, but to copy the icon name is a challenge

## Steps to reproduce

- Open the Fluent Emoji set:

https://icon-sets.iconify.design/fluent-emoji/?keyword=fluent

- Select an emoji like "artist 🧑‍🎨" (most of the emojis have lots of colors)

## Desired solution

Limit the height to half the screen and add a scroll to the div inside `footer-icons`

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed. When there are too many colors to edit, they will be hidden by default and button to show them will appear (same for opacity and stroke width). If they are shown (user clicked button), scrollbar will appear for the whole customisations section.

Fix will be deployed tomorrow.

Also, I recommend avoiding Fluent Emoji. Those icons have massive amount of gradients, resulting in very slow rendering. They are great as raster images, but as SVG performance is horribly slow.

**Comment by cyberalien** [comment]
Fix is now deployed.
